version: "3.9"
services:
  chanchito:
    build: 
     context: .
     dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - monguito
    volumes:
      - .:/home/app
  monguito:
    image: mongo
    ports:
      - "27030:27017"
    environment:  
      - MONGO_INITDB_ROOT_USERNAME=lean
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
       - mongo-data:/data/db
volumes:
  mongo-data: